### ISSUE TITLE
Update to 0.100.0+ config file structure

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/ansible-neogo-n3#41]
See NeoGo 0.100.0 changelog, addresses/protocol settings are a bit different now. Old ones are still supported for now, but will be gone eventually.

**Comment by 532910** [comment]
https://github.com/nspcc-dev/neo-go/pull/2827/files#r1097731586

I believe this should be changed before updating this ansible role.

**Comment by roman-khimov** [comment]
It can't. We have what we have in 0.100.0. And it's fine for our installations. If/when we change something there we'll update the role again. But we can't live with old role for long, compatibility mode can't last forever.

**Comment by roman-khimov** [comment]
Solved a long time ago.
