### ISSUE TITLE
Replace `--config` with `--config-file` neo-go CLI option to start the node

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/ansible-neogo-n3#47]
https://github.com/nspcc-dev/neo-go/pull/3014 introduces `--config-file` option instead of `--config` path combined with `-m`, `-t` and `-p` flags. So now we can have single parameter that specifies node config file instead of two separate parameters, e.g. here we can replace `{{ neogo__conf_dir }}` and `{{ neogo__network }}` with some single `{{ neogo__conf_file }}`:
https://github.com/nspcc-dev/ansible-neogo-n3/blob/5a3da674a6d5d58f74fc6b5707a579422091ed42/templates/docker-compose.yml.j2#L14

There may be a set of other cases where it can be applied.

Can be implemented after [0.102.0](https://github.com/nspcc-dev/neo-go/milestone/66) NeoGo release.

**Comment by 532910** [comment]
1. What is m t p?
2. Why should I change something here??
